### ISSUE TITLE
GAPI client sometimes not initialized correctly

### ISSUE THREAD

**Issue by jonathancai11** [rice-apps/match#10]
So.... the GAPI client is used for the Google OAuth sign in workflow, and for all the Google Sheets API calls.

It works like so:

In `public/index.html`, we initially load the Google code through a CDN:
https://github.com/rice-apps/match/blob/6fc118554c975ce6d77ac7f48001b6b03e05111e/public/index.html#L33-L39

The embedded js script above should dispatch the event "google-loaded" every time the google platform code is finished loading into our app.

Then in `Header.js` component, what I've done is have a `useEffect(func, [])` <- empty list as second arg so it only fires once, and the function just creates an event listener for "google-loaded". 
https://github.com/rice-apps/match/blob/6fc118554c975ce6d77ac7f48001b6b03e05111e/src/components/header/Header.js#L38-L42

If you see, the function calls `handleClientLoad`, which is in `util/gapi.js`:
https://github.com/rice-apps/match/blob/6fc118554c975ce6d77ac7f48001b6b03e05111e/src/util/gapi.js#L19-L46

This `handleClientLoad` function does the initialization by triggering `initClient`. 

However, see in `handleAuthClick`, that is where I catch if `window.gapi` is not loaded, then I call an alert. Basically if the script in html did not load in correctly, then `window.gapi` will not be initialized.

You should be asking: What's the point of the `useEffect`? And why don't I just call `window.addEventListener` from outside the React component?

The reason is, to install a callback function (take a look at the function `authenticationCallback`) that can modify Recoil state, we must have access to those React hooks (we want to add the user info to Recoil state once user logs in), which means we must call `handleClientLoad` from within the scope of a React component.

I am pretty sure the issue is with this weird work-around to install this callback func. I suspect that sometimes the `useEffect` call is not triggered before the google cdn in index.html is finished loading, so that the `handleClientLoad` doesn't get triggered, and `window.gapi` is not initialized.

There is pleeenty of documentation on how to use their google-api-javascript-client.

Google something like "google api javascript client initialization" or sth
 
Some potential solutions here:
https://github.com/google/google-api-javascript-client/issues/399

**Comment by rknightly** [comment]
Should be fixed!
Just added a check to see if the API has already loaded before creating the listener.

https://github.com/rice-apps/match/commit/625a199e3f3ca4bfc27d0e639f1100cbe220e2b4
https://github.com/rice-apps/match/commit/2aa15a72823ef6f53f403dc3f31c389a3824b99d

**Comment by jonathancai11** [comment]
So the issue was that it would create an event listener after the gapi client has been initialized?

**Comment by rknightly** [comment]
Yeah, not after the client had been initialized, but after the script finished loading. So the 'google-loaded' event was occurring before the event listener was created, since the file can load pretty quickly.

To test this, I added a short delay before creating the listener with
`window.addEventListener("google-loaded", () => handleClientLoad(authenticationCallback));`
and the issue was reproduced every time.

So, my fix was to check if the script has already loaded (and therefore the "google-loaded" event has already happened) before creating the listener. If the script has already loaded, we can just call handleClientLoad directly rather than waiting for the event:
```javascript
// Check if api is already loaded
if (window.gapi) {
    handleClientLoad(authenticationCallback);
} else { 
    // Not already loaded; create event listener
    console.log("creating event listener for google-loaded")
    window.addEventListener("google-loaded", () => handleClientLoad(authenticationCallback));
}
```

**Comment by jonathancai11** [comment]
Great work!!
