### ISSUE TITLE
CCD page 404s due to GCP build configuration

### ISSUE THREAD

**Issue by jonathancai11** [rice-apps/match#8]
![Screen Shot 2020-07-29 at 6 38 22 PM](https://user-images.githubusercontent.com/37007468/88870676-d2e45600-d1ca-11ea-9ff0-d3e2fa825f51.png)

To fix, you just need to add /ccd like the rest of the pages defined in app.yaml like below:

![Screen Shot 2020-07-29 at 6 38 31 PM](https://user-images.githubusercontent.com/37007468/88870698-e1327200-d1ca-11ea-980b-17e567e99e37.png)

* Be very careful about indentation when modifying this yaml file. A bad indent could stop this build from succeeding entirely. *

There is actually a nicer way to define the pages than hard-coding a list of them, but we can do that later..

**Comment by zawie** [comment]
It's done!
https://github.com/rice-apps/match/commit/8de520f0dcc12b5c3b3ff5a169e1de6519fd7237

**Comment by zawie** [comment]
It's done!
https://github.com/rice-apps/match/commit/8de520f0dcc12b5c3b3ff5a169e1de6519fd7237

**Comment by jonathancai11** [comment]
@zawie @rknightly Eventually you can try [this](https://github.com/jonathancai11/yourdesk-react/blob/master/client.yaml)

**Comment by jonathancai11** [comment]
Basically just regex the handlers
